
import {
  Siren,
  Waypoints,
  Truck,
  Flame,
  Droplets,
  Clipboard,
  HeartPulse,
  Search,
  Heart,
  PersonStanding,
  Shovel,
  Wind,
  Droplet,
  Cone,
  Building2,
  Wrench,
  LucideIcon,
  Construction,
  HardHat,
  ShieldAlert,
  Signpost,
  Megaphone,
} from 'lucide-react';

export type EventCategory = {
  name: string;
  title: string;
  slug: string;
  icon: LucideIcon;
  description: string;
  color: string;
};

export const eventCategories: EventCategory[] = [
  {
    name: 'QUD APH',
    title: 'QUD APH',
    slug: 'qud-aph',
    icon: Siren,
    description: 'Relatar QUD APH.',
    color: '#36454F',
  },
  {
    name: 'QUD OPERAÇÃO',
    title: 'QUD OPERAÇÃO',
    slug: 'qud-operacao',
    icon: Siren,
    description: 'Relatar QUD Operação.',
    color: '#000000',
  },
  {
    name: 'TRAÇADO DE PISTA',
    title: 'TRAÇADO DE PISTA',
    slug: 'tracado-de-pista',
    icon: Waypoints,
    description: 'Relatar traçado de pista.',
    color: '#FFA500',
  },
  {
    name: 'TO 01',
    title: 'VEÍCULO ABANDONADO',
    slug: 'to-01',
    icon: Truck,
    description: 'Relatório de Veículo Abandonado.',
    color: '#8B4513',
  },
  {
    name: 'TO 02',
    title: 'INCÊNDIO NA FAIXA DE DOMÍNIO/LINDEIRO',
    slug: 'to-02',
    icon: Flame,
    description: 'Relatório de Incêndio.',
    color: '#FF4500',
  },
  {
    name: 'TO 03',
    title: 'ANIMAL NA RODOVIA',
    slug: 'to-03',
    icon: Droplets,
    description: 'Relatar TO 03.',
    color: '#FFD700',
  },
  {
    name: 'TO 04',
    title: 'REMOÇÃO',
    slug: 'to-04',
    icon: Truck,
    description: 'Relatar TO 04.',
    color: '#8B4513',
  },
  {
    name: 'TO 05',
    title: 'INCÊNDIO VEICULAR',
    slug: 'to-05',
    icon: Flame,
    description: 'Relatar TO 05.',
    color: '#DC143C',
  },
  {
    name: 'TO 06',
    title: 'PANE SOBRE FAIXA DE ROLAMENTO',
    slug: 'to-06',
    icon: Truck,
    description: 'Relatar TO 06.',
    color: '#32CD32',
  },
  {
    name: 'TO 07',
    title: 'OBJETO NA PISTA',
    slug: 'to-07',
    icon: Cone,
    description: 'Relatar TO 07.',
    color: '#008080',
  },
  {
    name: 'TO 09',
    title: 'OBRAS NA RODOVIA/CONVERVAÇÃO DE ROTINA',
    slug: 'to-09',
    icon: HardHat,
    description: 'Relatar TO 09.',
    color: '#4682B4',
  },
  {
    name: 'TO 11',
    title: 'DANOS AO PATRIMÔNIO',
    slug: 'to-11',
    icon: ShieldAlert,
    description: 'Relatar Danos ao Patrimônio.',
    color: '#FF69B4',
  },
  {
    name: 'TO 12',
    title: 'ATENDIMENTO CLÍNICO',
    slug: 'to-12',
    icon: HeartPulse,
    description: 'Relatar TO 12.',
    color: '#DC143C',
  },
  {
    name: 'TO 15',
    title: 'VERIFICAÇÃO FAIXA DE DOMÍNIO',
    slug: 'to-15',
    icon: Search,
    description: 'Relatar TO 15.',
    color: '#1E90FF',
  },
  {
    name: 'TO 16',
    title: 'ATENDIMENTO A FUNCIONÁRIO',
    slug: 'to-16',
    icon: Heart,
    description: 'Relatar TO 16.',
    color: '#9370DB',
  },
  {
    name: 'TO 17',
    title: 'ANDARILHO NA RODOVIA',
    slug: 'to-17',
    icon: PersonStanding,
    description: 'Relatar TO 17.',
    color: '#8B0000',
  },
  {
    name: 'TO 19',
    title: 'TO 19',
    slug: 'to-19',
    icon: Siren,
    description: 'Relatar TO 19.',
    color: '#4682B4',
  },
  {
    name: 'TO 33',
    title: 'VEÍCULO ATOLADO',
    slug: 'to-33',
    icon: Shovel,
    description: 'Relatar TO 33.',
    color: '#808080',
  },
  {
    name: 'TO 34',
    title: 'BURACO NA RODOVIA',
    slug: 'to-34',
    icon: Wrench,
    description: 'Relatar TO 34.',
    color: '#EE82EE',
  },
  {
    name: 'TO 35',
    title: 'ÓLEO SOBRE A PISTA',
    slug: 'to-35',
    icon: Droplet,
    description: 'Relatar TO 35.',
    color: '#FFFF00',
  },
  {
    name: 'TO 37',
    title: 'SINALIZAÇÃO VERTICAL',
    slug: 'to-37',
    icon: Signpost,
    description: 'Relatar TO 37.',
    color: '#FF6347',
  },
  {
    name: 'TO 38',
    title: 'PLACAS DE PROPAGANDA',
    slug: 'to-38',
    icon: Megaphone,
    description: 'Relatar TO 38.',
    color: '#3CB371',
  },
  {
    name: 'TO 39',
    title: 'DESTOMBAMENTO DE VEÍCULO',
    slug: 'to-39',
    icon: Wrench,
    description: 'Relatar TO 39.',
    color: '#6A5ACD',
  },
  {
    name: 'TO 50',
    title: 'NÍVEL DE SERVIÇOS, MANUTENÇÃO/BASES',
    slug: 'to-50',
    icon: Wrench,
    description: 'Relatar Nível de Serviços, Manutenção/Bases.',
    color: '#191970',
  },
];
