// This file is automatically generated. Do not modify it manually.
// For any changes, please modify the corresponding file in the docs/ folder.
export const firebaseConfig = {
  "apiKey": "mock-key-for-testing",
  "authDomain": "mock-key-for-testing",
  "projectId": "mock-key-for-testing",
  "storageBucket": "mock-key-for-testing",
  "messagingSenderId": "mock-key-for-testing",
  "appId": "mock-key-for-testing",
  "measurementId": "mock-key-for-testing"
};
